onlyBuiltDependencies:
  - '@alcalzone/ansi-tokenize'
  - '@babel/code-frame'
  - '@babel/helper-validator-identifier'
  - '@babel/highlight'
  - '@base2/pretty-print-object'
  - '@bcoe/v8-coverage'
  - '@cspotcode/source-map-support'
  - '@eslint-community/eslint-utils'
  - '@eslint-community/regexpp'
  - '@eslint/config-array'
  - '@eslint/config-helpers'
  - '@eslint/core'
  - '@eslint/eslintrc'
  - '@eslint/js'
  - '@eslint/object-schema'
  - '@eslint/plugin-kit'
  - '@fastify/ajv-compiler'
  - '@fastify/error'
  - '@fastify/fast-json-stringify-compiler'
  - '@fastify/forwarded'
  - '@fastify/merge-json-schemas'
  - '@fastify/proxy-addr'
  - '@humanfs/core'
  - '@humanfs/node'
  - '@humanwhocodes/module-importer'
  - '@humanwhocodes/retry'
  - '@isaacs/cliui'
  - '@isaacs/ts-node-temp-fork-for-pr-2009'
  - '@istanbuljs/schema'
  - '@jest/expect-utils'
  - '@jest/schemas'
  - '@jest/types'
  - '@jridgewell/resolve-uri'
  - '@jridgewell/sourcemap-codec'
  - '@jridgewell/trace-mapping'
  - '@nodelib/fs.scandir'
  - '@nodelib/fs.stat'
  - '@nodelib/fs.walk'
  - '@npmcli/agent'
  - '@npmcli/fs'
  - '@npmcli/git'
  - '@npmcli/installed-package-contents'
  - '@npmcli/node-gyp'
  - '@npmcli/package-json'
  - '@npmcli/promise-spawn'
  - '@npmcli/redact'
  - '@npmcli/run-script'
  - '@pkgjs/parseargs'
  - '@pkgr/core'
  - '@sigstore/bundle'
  - '@sigstore/core'
  - '@sigstore/protobuf-specs'
  - '@sigstore/sign'
  - '@sigstore/tuf'
  - '@sigstore/verify'
  - '@sinclair/typebox'
  - '@tapjs/after'
  - '@tapjs/after-each'
  - '@tapjs/asserts'
  - '@tapjs/before'
  - '@tapjs/before-each'
  - '@tapjs/chdir'
  - '@tapjs/config'
  - '@tapjs/core'
  - '@tapjs/error-serdes'
  - '@tapjs/filter'
  - '@tapjs/fixture'
  - '@tapjs/intercept'
  - '@tapjs/mock'
  - '@tapjs/node-serialize'
  - '@tapjs/processinfo'
  - '@tapjs/reporter'
  - '@tapjs/run'
  - '@tapjs/snapshot'
  - '@tapjs/spawn'
  - '@tapjs/stack'
  - '@tapjs/stdin'
  - '@tapjs/test'
  - '@tapjs/typescript'
  - '@tapjs/worker'
  - '@tsconfig/node14'
  - '@tsconfig/node16'
  - '@tsconfig/node18'
  - '@tsconfig/node20'
  - '@tufjs/canonical-json'
  - '@tufjs/models'
  - '@types/eslint'
  - '@types/estree'
  - '@types/istanbul-lib-coverage'
  - '@types/istanbul-lib-report'
  - '@types/istanbul-reports'
  - '@types/json-schema'
  - '@types/node'
  - '@types/stack-utils'
  - '@types/yargs'
  - '@types/yargs-parser'
  - '@typescript-eslint/eslint-plugin'
  - '@typescript-eslint/parser'
  - '@typescript-eslint/scope-manager'
  - '@typescript-eslint/type-utils'
  - '@typescript-eslint/types'
  - '@typescript-eslint/typescript-estree'
  - '@typescript-eslint/utils'
  - '@typescript-eslint/visitor-keys'
  - abbrev
  - abort-controller
  - abstract-logging
  - acorn
  - acorn-jsx
  - acorn-walk
  - agent-base
  - aggregate-error
  - ajv
  - ajv-formats
  - ansi-escapes
  - ansi-regex
  - ansi-styles
  - anymatch
  - arg
  - argparse
  - async-hook-domain
  - atomic-sleep
  - auto-bind
  - avvio
  - balanced-match
  - base64-js
  - binary-extensions
  - brace-expansion
  - braces
  - buffer
  - c8
  - cacache
  - callsites
  - chalk
  - chokidar
  - chownr
  - ci-info
  - clean-stack
  - cli-boxes
  - cli-cursor
  - cli-truncate
  - cliui
  - code-excerpt
  - color-convert
  - color-name
  - concat-map
  - convert-source-map
  - convert-to-spaces
  - cookie
  - cross-spawn
  - debug
  - deep-is
  - diff
  - diff-sequences
  - eastasianwidth
  - emoji-regex
  - encoding
  - env-paths
  - environment
  - err-code
  - es-toolkit
  - escalade
  - escape-string-regexp
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - eslint-scope
  - eslint-visitor-keys
  - espree
  - esquery
  - esrecurse
  - estraverse
  - esutils
  - event-target-shim
  - events
  - events-to-array
  - expect
  - exponential-backoff
  - fast-decode-uri-component
  - fast-deep-equal
  - fast-diff
  - fast-glob
  - fast-json-stable-stringify
  - fast-json-stringify
  - fast-levenshtein
  - fast-querystring
  - fast-redact
  - fast-uri
  - fastify
  - fastq
  - file-entry-cache
  - fill-range
  - find-my-way
  - find-up
  - flat-cache
  - flatted
  - foreground-child
  - fromentries
  - fs-minipass
  - function-loop
  - get-caller-file
  - get-east-asian-width
  - get-port
  - glob
  - glob-parent
  - globals
  - graceful-fs
  - graphemer
  - has-flag
  - hosted-git-info
  - html-escaper
  - http-cache-semantics
  - http-proxy-agent
  - https-proxy-agent
  - iconv-lite
  - ieee754
  - ignore
  - ignore-by-default
  - ignore-walk
  - import-fresh
  - imurmurhash
  - indent-string
  - ini
  - ink
  - ip-address
  - ipaddr.js
  - is-actual-promise
  - is-binary-path
  - is-extglob
  - is-fullwidth-code-point
  - is-glob
  - is-in-ci
  - is-lambda
  - is-number
  - is-plain-object
  - isexe
  - istanbul-lib-coverage
  - istanbul-lib-report
  - istanbul-reports
  - jackspeak
  - jest-diff
  - jest-get-type
  - jest-matcher-utils
  - jest-message-util
  - jest-util
  - js-tokens
  - js-yaml
  - jsbn
  - json-buffer
  - json-parse-even-better-errors
  - json-schema-ref-resolver
  - json-schema-traverse
  - json-stable-stringify-without-jsonify
  - jsonparse
  - keyv
  - levn
  - light-my-request
  - locate-path
  - lodash.merge
  - loose-envify
  - lru-cache
  - make-dir
  - make-error
  - make-fetch-happen
  - merge2
  - micromatch
  - mimic-fn
  - minimatch
  - minipass
  - minipass-collect
  - minipass-fetch
  - minipass-flush
  - minipass-pipeline
  - minipass-sized
  - minizlib
  - mkdirp
  - ms
  - natural-compare
  - negotiator
  - node-gyp
  - nodemon
  - nopt
  - normalize-package-data
  - normalize-path
  - npm-bundled
  - npm-install-checks
  - npm-normalize-package-bin
  - npm-package-arg
  - npm-packlist
  - npm-pick-manifest
  - npm-registry-fetch
  - on-exit-leak-free
  - onetime
  - opener
  - optionator
  - p-limit
  - p-locate
  - p-map
  - package-json-from-dist
  - pacote
  - parent-module
  - patch-console
  - path-exists
  - path-key
  - path-scurry
  - picomatch
  - pino
  - pino-abstract-transport
  - pino-std-serializers
  - pirates
  - polite-json
  - prelude-ls
  - prettier
  - prettier-linter-helpers
  - pretty-format
  - prismjs
  - prismjs-terminal
  - proc-log
  - process
  - process-on-spawn
  - process-warning
  - promise-inflight
  - promise-retry
  - pstree.remy
  - punycode
  - queue-microtask
  - quick-format-unescaped
  - react
  - react-dom
  - react-element-to-jsx-string
  - react-is
  - react-reconciler
  - readable-stream
  - readdirp
  - real-require
  - require-directory
  - require-from-string
  - resolve-from
  - resolve-import
  - restore-cursor
  - ret
  - retry
  - reusify
  - rfdc
  - rimraf
  - run-parallel
  - safe-buffer
  - safe-regex2
  - safe-stable-stringify
  - safer-buffer
  - scheduler
  - secure-json-parse
  - semver
  - set-cookie-parser
  - shebang-command
  - shebang-regex
  - signal-exit
  - sigstore
  - simple-update-notifier
  - slash
  - slice-ansi
  - smart-buffer
  - socks
  - socks-proxy-agent
  - sonic-boom
  - spdx-correct
  - spdx-exceptions
  - spdx-expression-parse
  - spdx-license-ids
  - split2
  - sprintf-js
  - ssri
  - stack-utils
  - string-length
  - string-width
  - string_decoder
  - strip-ansi
  - strip-json-comments
  - supports-color
  - sync-content
  - synckit
  - tap
  - tap-parser
  - tap-yaml
  - tar
  - tcompare
  - test-exclude
  - thread-stream
  - to-regex-range
  - toad-cache
  - touch
  - trivial-deferred
  - ts-api-utils
  - tshy
  - tslib
  - tuf-js
  - type-check
  - type-fest
  - typescript
  - undefsafe
  - undici-types
  - unique-filename
  - unique-slug
  - uri-js
  - utap
  - uuid
  - v8-compile-cache-lib
  - v8-to-istanbul
  - validate-npm-package-license
  - validate-npm-package-name
  - walk-up-path
  - which
  - widest-line
  - word-wrap
  - wrap-ansi
  - ws
  - y18n
  - yallist
  - yaml
  - yaml-types
  - yargs
  - yargs-parser
  - yocto-queue
  - yoga-wasm-web
